# This is a basic workflow to help you get started with Actions

name: Bottle Tunnelto

on: 
  workflow_dispatch:
    inputs:
      versionString:
        description: 'The version semver string like 0.1.14'     
        required: true  

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      # Runs a set of commands using the runners shell
      - name: Update version
        run: |
          cp tunnelto.rb.template tunnelto.rb
          curl -s -L "https://github.com/agrinman/tunnelto/archive/${{ github.event.inputs.versionString }}.zip" | shasum -b -a 256 | head -c 40 > CODE_HASH
          curl -s -L "https://github.com/agrinman/tunnelto/releases/download/${{ github.event.inputs.versionString }}.zip" | shasum -b -a 256 | head -c 40 > BIN_HASH
          sed -i -e 's/_VERSION_/${{ github.event.inputs.versionString }}/g' tunnelto.rb
          sed -i -e "s/_CODE_HASH_/$(cat BIN_HASH)/g" tunnelto.rb          
          sed -i -e "s/_BIN_SHA2_/$(cat BIN_HASH)/g" tunnelto.rb

      - name: Add & Commit
        uses: EndBug/add-and-commit@v7.1.2
        with:
          branch: master
          message: "Update version to ${{ github.event.inputs.versionString }}"
          pull_strategy: 'NO-PULL'
          add: 'tunnelto.rb'


