# This is a basic workflow to help you get started with Actions

name: Bottle Tunnelto

on: 
  workflow_dispatch:
    inputs:
      versionString:
        description: 'The version semver string like 0.1.14'     
        required: true  

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      # Runs a set of commands using the runners shell
      - name: Update version
        run: |
          cp tunnelto.rb.template tunnelto.rb
          export BIN_URL="https://github.com/agrinman/tunnelto/releases/download/${{ github.event.inputs.versionString }}/tunnelto-${{ github.event.inputs.versionString }}.big_sur.bottle.tar.gz"
          curl -s -L "https://github.com/agrinman/tunnelto/archive/${{ github.event.inputs.versionString }}.zip" | shasum -b -a 256 | head -c 64 > CODE_HASH
          curl -s -L "$BIN_URL" | shasum -b -a 256 | head -c 64 > BIN_HASH
          sed -i -e 's/_VERSION_/${{ github.event.inputs.versionString }}/g' tunnelto.rb
          sed -i -e "s/_CODE_SHA2_/$(cat CODE_HASH)/g" tunnelto.rb          
          sed -i -e "s/_BIN_SHA2_/$(cat BIN_HASH)/g" tunnelto.rb
          rm CODE_HASH BIN_HASH
          
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          title: "Tunnelto ${{ github.event.inputs.versionString }}"
          body: "Update version to ${{ github.event.inputs.versionString }}"


